# This file stores configurations for your Shopify app.

scopes = "write_products,read_products,read_content,write_content,read_product_listings,read_themes,write_themes,read_orders,write_orders,read_all_orders,read_customers,write_customers,read_files,write_files,read_inventory,write_inventory,read_locations,read_resource_feedbacks,write_resource_feedbacks,read_script_tags,write_script_tags,read_shipping,write_shipping"
